export interface BibleVerse {
  text: string;
  reference: string;
}

export const BIBLE_VERSES: BibleVerse[] = [
  { text: "Sebab di mana dua atau tiga orang berkumpul dalam Nama-Ku, di situ Aku ada di tengah-tengah mereka.", reference: "Matius 18:20" },
  { text: "Tak berkesudahan kasih setia TUHAN, tak habis-habisnya rahmat-Nya, selalu baru tiap pagi; besar keesaan-Mu!", reference: "Ratapan 3:22-23" },
  { text: "TUHAN adalah gembalaku, takkan kekurangan aku. Ia membaringkan aku di padang yang berumput hijau.", reference: "Mazmur 23:1-2" },
  { text: "Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku.", reference: "Filipi 4:13" },
  { text: "Janganlah hendaknya kamu kuatir tentang apapun juga, tetapi nyatakanlah dalam segala hal keinginanmu kepada Allah dalam doa dan permohonan dengan ucapan syukur.", reference: "Filipi 4:6" },
  { text: "Sebab Aku ini mengetahui rancangan-rancangan apa yang ada pada-Ku mengenai kamu, demikianlah firman TUHAN, yaitu rancangan damai sejahtera dan bukan rancangan kecelakaan, untuk memberikan kepadamu hari depan yang penuh harapan.", reference: "Yeremia 29:11" },
  { text: "Percayalah kepada TUHAN dengan segenap hatimu, dan janganlah bersandar kepada pengertianmu sendiri.", reference: "Amsal 3:5" },
  { text: "Dalam segala jalanmu akuilah Dia, maka Ia akan meluruskan jalanmu.", reference: "Amsal 3:6" },
  { text: "Tetapi orang-orang yang menanti-nantikan TUHAN mendapat kekuatan baru: mereka seumpama rajawali yang naik terbang dengan kekuatan sayapnya.", reference: "Yesaya 40:31" },
  { text: "Damai sejahtera Kutinggalkan bagimu. Damai sejahtera-Ku Kuberikan kepadamu, dan apa yang Kuberikan tidak seperti yang diberikan oleh dunia kepadamu.", reference: "Yohanes 14:27" },
  { text: "Marilah kepada-Ku, semua yang letih lesu dan berbeban berat, Aku akan memberi kelegaan kepadamu.", reference: "Matius 11:28" },
  { text: "Serahkanlah segala kekuatiranmu kepada-Nya, sebab Ia yang memelihara kamu.", reference: "1 Petrus 5:7" },
  { text: "TUHAN itu baik; tempat perlindungan pada waktu kesusahan; Ia mengenal orang-orang yang berlindung kepada-Nya.", reference: "Nahum 1:7" },
  { text: "Kasih itu sabar; kasih itu murah hati; ia tidak cemburu; ia tidak memegahkan diri dan tidak sombong.", reference: "1 Korintus 13:4" },
  { text: "Bersukacitalah senantiasa. Tetaplah berdoa. Mengucap syukurlah dalam segala hal.", reference: "1 Tesalonika 5:16-18" },
  { text: "Firman-Mu itu pelita bagi kakiku dan terang bagi jalanku.", reference: "Mazmur 119:105" },
  { text: "Allah itu bagi kita tempat perlindungan dan kekuatan, sebagai penolong dalam kesesakan sangat terbukti.", reference: "Mazmur 46:2" },
  { text: "Kiranya TUHAN memberkati engkau dan melindungi engkau; TUHAN menyinari engkau dengan wajah-Nya dan memberi engkau kasih karunia.", reference: "Bilangan 6:24-25" },
  { text: "Kita tahu sekarang, bahwa Allah turut bekerja dalam segala sesuatu untuk mendatangkan kebaikan bagi mereka yang mengasihi Dia.", reference: "Roma 8:28" },
  { text: "Jika Allah di pihak kita, siapakah yang akan melawan kita?", reference: "Roma 8:31" },
  { text: "Hendaklah kamu kuat di dalam Tuhan, di dalam kekuatan kuasa-Nya.", reference: "Efesus 6:10" },
  { text: "Segala tulisan yang diilhamkan Allah memang bermanfaat untuk mengajar, untuk menyatakan kesalahan, untuk memperbaiki kelakuan dan untuk mendidik orang dalam kebenaran.", reference: "2 Timotius 3:16" },
  { text: "Hati yang gembira adalah obat yang manjur, tetapi semangat yang patah mengeringkan tulang.", reference: "Amsal 17:22" },
  { text: "Karena masa depan sungguh ada, dan harapanmu tidak akan hilang.", reference: "Amsal 23:18" },
  { text: "Carilah dahulu Kerajaan Allah dan kebenarannya, maka semuanya itu akan ditambahkan kepadamu.", reference: "Matius 6:33" },
  { text: "Janganlah kamu kuatir akan hari besok, karena hari besok mempunyai kesusahannya sendiri.", reference: "Matius 6:34" },
  { text: "Mintalah, maka akan diberikan kepadamu; carilah, maka kamu akan mendapat; ketoklah, maka pintu akan dibukakan bagimu.", reference: "Matius 7:7" },
  { text: "Akulah jalan dan kebenaran dan hidup. Tidak ada seorangpun yang datang kepada Bapa, kalau tidak melalui Aku.", reference: "Yohanes 14:6" },
  { text: "Jikalau kamu tinggal di dalam Aku dan firman-Ku tinggal di dalam kamu, mintalah apa saja yang kamu kehendaki, dan kamu akan menerimanya.", reference: "Yohanes 15:7" },
  { text: "Bukan kamu yang memilih Aku, tetapi Akulah yang memilih kamu.", reference: "Yohanes 15:16" },
  { text: "Semuanya itu Kukatakan kepadamu, supaya kamu beroleh damai sejahtera dalam Aku. Dalam dunia kamu menderita penganiayaan, tetapi kuatkanlah hatimu, Aku telah mengalahkan dunia.", reference: "Yohanes 16:33" },
  { text: "Sebab upah dosa ialah maut; tetapi karunia Allah ialah hidup yang kekal dalam Kristus Yesus, Tuhan kita.", reference: "Roma 6:23" },
  { text: "Sebab jika kamu mengaku dengan mulutmu, bahwa Yesus adalah Tuhan, dan percaya dalam hatimu, bahwa Allah telah membangkitkan Dia dari antara orang mati, maka kamu akan diselamatkan.", reference: "Roma 10:9" },
  { text: "Iman adalah dasar dari segala sesuatu yang kita harapkan dan bukti dari segala sesuatu yang tidak kita lihat.", reference: "Ibrani 11:1" },
  { text: "Mendekatlah kepada Allah, dan Ia akan mendekat kepadamu.", reference: "Yakobus 4:8" },
  { text: "Doa orang yang benar, bila dengan yakin didoakan, sangat besar kuasanya.", reference: "Yakobus 5:16" },
  { text: "TUHAN adalah terangku dan keselamatanku, kepada siapakah aku harus takut?", reference: "Mazmur 27:1" },
  { text: "Nantikanlah TUHAN! Kuatkanlah dan teguhkanlah hatimu! Ya, nantikanlah TUHAN!", reference: "Mazmur 27:14" },
  { text: "TUHAN adalah kekuatanku dan perisaiku; kepada-Nya hatiku percaya. Aku tertolong sebab itu beria-ria hatiku.", reference: "Mazmur 28:7" },
  { text: "Kecaplah dan lihatlah, betapa baiknya TUHAN itu! Berbahagialah orang yang berlindung pada-Nya!", reference: "Mazmur 34:9" },
  { text: "TUHAN itu dekat kepada orang-orang yang patah hati, dan Ia menyelamatkan orang-orang yang remuk jiwanya.", reference: "Mazmur 34:19" },
  { text: "Serahkanlah hidupmu kepada TUHAN dan percayalah kepada-Nya, dan Ia akan bertindak.", reference: "Mazmur 37:5" },
  { text: "Berdiam dirilah di hadapan TUHAN dan nantikanlah Dia.", reference: "Mazmur 37:7" },
  { text: "Jadikanlah hatiku tahir, ya Allah, dan perbaharuilah batinku dengan roh yang teguh!", reference: "Mazmur 51:12" },
  { text: "Serahkanlah kuatirmu kepada TUHAN, maka Ia akan memelihara engkau!", reference: "Mazmur 55:23" },
  { text: "Hanya dekat Allah saja aku tenang, dari pada-Nyalah keselamatanku.", reference: "Mazmur 62:2" },
  { text: "Sungguh, hatiku haus kepada Allah, kepada Allah yang hidup.", reference: "Mazmur 42:3" },
  { text: "Pujilah TUHAN, hai jiwaku, dan janganlah lupakan segala kebaikan-Nya!", reference: "Mazmur 103:2" },
  { text: "Sejauh timur dari barat, demikian dijauhkan-Nya dari pada kita pelanggaran kita.", reference: "Mazmur 103:12" },
  { text: "Bersyukurlah kepada TUHAN, sebab Ia baik! Bahwasanya untuk selama-lamanya kasih setia-Nya.", reference: "Mazmur 107:1" },
  { text: "Aku melayangkan mataku ke gunung-gunung; dari manakah akan datang pertolonganku? Pertolonganku ialah dari TUHAN, yang menjadikan langit dan bumi.", reference: "Mazmur 121:1-2" },
  { text: "TUHAN akan menjaga keluar masukmu, dari sekarang sampai selama-lamanya.", reference: "Mazmur 121:8" },
  { text: "Orang-orang yang menabur dengan mencucurkan air mata, akan menuai dengan bersorak-sorai.", reference: "Mazmur 126:5" },
  { text: "Jikalau bukan TUHAN yang membangun rumah, sia-sialah usaha orang yang membangunnya.", reference: "Mazmur 127:1" },
  { text: "Selidikilah aku, ya Allah, dan kenallah hatiku, ujilah aku dan kenallah pikiran-pikiranku.", reference: "Mazmur 139:23" },
  { text: "Biarlah segala yang bernafas memuji TUHAN! Haleluya!", reference: "Mazmur 150:6" },
  { text: "Takut akan TUHAN adalah permulaan pengetahuan, tetapi orang bodoh menghina hikmat dan didikan.", reference: "Amsal 1:7" },
  { text: "Jagalah hatimu dengan segala kewaspadaan, karena dari situlah terpancar kehidupan.", reference: "Amsal 4:23" },
  { text: "Nama TUHAN adalah menara yang kuat, ke sanalah orang benar berlari dan ia menjadi selamat.", reference: "Amsal 18:10" },
  { text: "Banyaklah rancangan di hati manusia, tetapi keputusan TUHANlah yang terlaksana.", reference: "Amsal 19:21" },
  { text: "Pada mulanya Allah menciptakan langit dan bumi.", reference: "Kejadian 1:1" },
  { text: "TUHAN memberkati engkau dari Sion, supaya engkau melihat kebahagiaan Yerusalem seumur hidupmu.", reference: "Mazmur 128:5" },
  { text: "Kasih setia TUHAN dari selama-lamanya sampai selama-lamanya atas orang-orang yang takut akan Dia.", reference: "Mazmur 103:17" },
  { text: "Bersyukurlah kepada TUHAN, panggillah nama-Nya, perkenalkanlah perbuatan-Nya di antara bangsa-bangsa!", reference: "1 Tawarikh 16:8" },
  { text: "Kuatkan dan teguhkanlah hatimu! Jangan takut dan jangan gemetar, sebab TUHAN Allahmu menyertai engkau.", reference: "Ulangan 31:6" },
  { text: "Bukankah telah Kuperintahkan kepadamu: kuatkan dan teguhkanlah hatimu? Janganlah kecut dan tawar hati.", reference: "Yosua 1:9" },
  { text: "Batu yang dibuang oleh tukang-tukang bangunan telah menjadi batu penjuru.", reference: "Mazmur 118:22" },
  { text: "Inilah hari yang dijadikan TUHAN, marilah kita bersorak-sorak dan bersukacita karenanya!", reference: "Mazmur 118:24" },
  { text: "Terpujilah TUHAN, hari demi hari Ia menanggung beban kita; Allah adalah keselamatan kita.", reference: "Mazmur 68:20" },
  { text: "Sebab TUHAN Allah adalah matahari dan perisai; kasih dan kemuliaan Ia berikan.", reference: "Mazmur 84:12" },
  { text: "Ajarlah kami menghitung hari-hari kami sedemikian, hingga kami beroleh hati yang bijaksana.", reference: "Mazmur 90:12" },
  { text: "Kenyangkanlah kami di waktu pagi dengan kasih setia-Mu, supaya kami bersorak-sorai dan bersukacita.", reference: "Mazmur 90:14" },
  { text: "Orang yang duduk dalam lindungan Yang Mahatinggi dan bermalam dalam naungan Yang Mahakuasa akan berkata kepada TUHAN: Tempat perlindunganku dan kubu pertahananku.", reference: "Mazmur 91:1-2" },
  { text: "Walau seribu orang rebah di sisimu, dan sepuluh ribu di sebelah kananmu, tetapi itu tidak akan menimpamu.", reference: "Mazmur 91:7" },
  { text: "Sebab malaikat-malaikat-Nya akan diperintahkan-Nya kepadamu untuk menjaga engkau di segala jalanmu.", reference: "Mazmur 91:11" },
  { text: "Masuklah melalui pintu gerbang-Nya dengan nyanyian syukur, ke dalam pelataran-Nya dengan puji-pujian.", reference: "Mazmur 100:4" },
  { text: "Sebab TUHAN itu baik, kasih setia-Nya untuk selama-lamanya, dan kesetiaan-Nya turun-temurun.", reference: "Mazmur 100:5" },
  { text: "Kasih setia-Mu, ya TUHAN, kiranya menyertai kami, seperti kami berharap kepada-Mu.", reference: "Mazmur 33:22" },
  { text: "TUHAN itu Pengasih dan Penyayang, panjang sabar dan besar kasih setia-Nya.", reference: "Mazmur 145:8" },
  { text: "TUHAN dekat pada setiap orang yang berseru kepada-Nya dalam kesetiaan.", reference: "Mazmur 145:18" },
  { text: "Ia menyembuhkan orang-orang yang patah hati dan membalut luka-luka mereka.", reference: "Mazmur 147:3" },
  { text: "Rancangan orang rajin semata-mata mendatangkan kelimpahan, tetapi setiap orang yang tergesa-gesa hanya akan mengalami kekurangan.", reference: "Amsal 21:5" },
  { text: "Nama baik lebih berharga dari pada kekayaan besar, dikasihi orang lebih baik dari pada perak dan emas.", reference: "Amsal 22:1" },
  { text: "Didiklah orang muda menurut jalan yang patut baginya, maka pada masa tuanya pun ia tidak akan menyimpang dari pada jalan itu.", reference: "Amsal 22:6" },
  { text: "Siapa menaruh belas kasihan kepada orang lemah, memiutangi TUHAN, yang akan membalas perbuatannya itu.", reference: "Amsal 19:17" },
  { text: "Perkataan yang menyenangkan adalah seperti sarang madu, manis bagi jiwa dan obat bagi tulang-tulang.", reference: "Amsal 16:24" },
  { text: "Hati manusia memikir-mikirkan jalannya, tetapi TUHANlah yang menentukan arah langkahnya.", reference: "Amsal 16:9" },
  { text: "Komitmenkanlah perbuatanmu kepada TUHAN, maka terlaksanalah segala rencanamu.", reference: "Amsal 16:3" },
  { text: "Kecongkakan mendahului kehancuran, dan tinggi hati mendahului kejatuhan.", reference: "Amsal 16:18" },
  { text: "Besi menajamkan besi, orang menajamkan sesamanya.", reference: "Amsal 27:17" },
  { text: "Seperti air mencerminkan wajah, demikianlah hati manusia mencerminkan manusia itu.", reference: "Amsal 27:19" },
  { text: "Untuk segala sesuatu ada masanya, untuk apapun di bawah langit ada waktunya.", reference: "Pengkhotbah 3:1" },
  { text: "Ia membuat segala sesuatu indah pada waktunya, bahkan Ia memberikan kekekalan dalam hati mereka.", reference: "Pengkhotbah 3:11" },
  { text: "Berdua lebih baik dari pada seorang diri, karena mereka menerima upah yang baik dalam jerih payah mereka.", reference: "Pengkhotbah 4:9" },
  { text: "Tali tiga lembar tak mudah diputuskan.", reference: "Pengkhotbah 4:12" },
  { text: "Bangkitlah, menjadi teranglah, sebab terangmu datang, dan kemuliaan TUHAN terbit atasmu.", reference: "Yesaya 60:1" },
  { text: "Janganlah takut, sebab Aku menyertai engkau, janganlah bimbang, sebab Aku ini Allahmu; Aku akan meneguhkan, bahkan akan menolong engkau.", reference: "Yesaya 41:10" },
  { text: "Sebab Aku ini, TUHAN, Allahmu, memegang tangan kananmu dan berkata kepadamu: Janganlah takut, Akulah yang menolong engkau.", reference: "Yesaya 41:13" },
  { text: "Lihat, Aku hendak membuat sesuatu yang baru, yang sekarang sudah tumbuh, belumkah kamu mengetahuinya?", reference: "Yesaya 43:19" },
  { text: "Tetapi dia tertikam oleh karena pemberontakan kita, dia diremukkan oleh karena kejahatan kita; ganjaran yang mendatangkan keselamatan bagi kita ditimpakan kepadanya, dan oleh bilur-bilurnya kita menjadi sembuh.", reference: "Yesaya 53:5" },
  { text: "Carilah TUHAN selama Ia berkenan ditemui; berserulah kepada-Nya selama Ia dekat!", reference: "Yesaya 55:6" },
  { text: "Sebab rancangan-Ku bukanlah rancanganmu, dan jalanmu bukanlah jalan-Ku, demikianlah firman TUHAN.", reference: "Yesaya 55:8" },
  { text: "Demikianlah firman-Ku yang keluar dari mulut-Ku: ia tidak akan kembali kepada-Ku dengan sia-sia, tetapi ia akan melaksanakan apa yang Kukehendaki.", reference: "Yesaya 55:11" },
  { text: "Berserulah kepada-Ku, maka Aku akan menjawab engkau dan akan memberitahukan kepadamu hal-hal yang besar dan yang tidak terpahami.", reference: "Yeremia 33:3" },
  { text: "Diberkatilah orang yang mengandalkan TUHAN, yang menaruh harapannya pada TUHAN!", reference: "Yeremia 17:7" },
  { text: "Sembuhkanlah aku, ya TUHAN, maka aku akan sembuh; selamatkanlah aku, maka aku akan selamat, sebab Engkaulah kepujianku!", reference: "Yeremia 17:14" },
  { text: "Bukan dengan keperkasaan dan bukan dengan kekuatan, melainkan dengan roh-Ku, firman TUHAN semesta alam.", reference: "Zakharia 4:6" },
  { text: "Hai manusia, telah diberitahukan kepadamu apa yang baik. Dan apakah yang dituntut TUHAN dari padamu: selain berlaku adil, mencintai kesetiaan, dan hidup dengan rendah hati di hadapan Allahmu?", reference: "Mikha 6:8" },
  { text: "TUHAN Allahmu ada di antaramu sebagai pahlawan yang memberi kemenangan. Ia bergirang karena engkau dengan sukacita.", reference: "Zefanya 3:17" },
  { text: "Bawalah seluruh persembahan persepuluhan ke dalam rumah perbendaharaan... dan ujilah Aku, firman TUHAN semesta alam, apakah Aku tidak membukakan bagimu tingkap-tingkap langit.", reference: "Maleakhi 3:10" },
  { text: "Berbahagialah orang yang miskin di hadapan Allah, karena merekalah yang empunya Kerajaan Sorga.", reference: "Matius 5:3" },
  { text: "Berbahagialah orang yang berdukacita, karena mereka akan dihibur.", reference: "Matius 5:4" },
  { text: "Berbahagialah orang yang lemah lembut, karena mereka akan memiliki bumi.", reference: "Matius 5:5" },
  { text: "Berbahagialah orang yang lapar dan haus akan kebenaran, karena mereka akan dipuaskan.", reference: "Matius 5:6" },
  { text: "Berbahagialah orang yang murah hatinya, karena mereka akan beroleh kemurahan.", reference: "Matius 5:7" },
  { text: "Berbahagialah orang yang suci hatinya, karena mereka akan melihat Allah.", reference: "Matius 5:8" },
  { text: "Berbahagialah orang yang membawa damai, karena mereka akan disebut anak-anak Allah.", reference: "Matius 5:9" },
  { text: "Kamu adalah garam dunia... Kamu adalah terang dunia.", reference: "Matius 5:13-14" },
  { text: "Demikianlah hendaknya terangmu bercahaya di depan orang, supaya mereka melihat perbuatanmu yang baik dan memuliakan Bapamu yang di sorga.", reference: "Matius 5:16" },
  { text: "Berikanlah kami pada hari ini makanan kami yang secukupnya dan ampunilah kami akan kesalahan kami.", reference: "Matius 6:11-12" },
  { text: "Karena di mana hartamu berada, di situ juga hatimu berada.", reference: "Matius 6:21" },
  { text: "Karena bagi Allah tidak ada yang mustahil.", reference: "Lukas 1:37" },
  { text: "Kemuliaan bagi Allah di tempat yang mahatinggi dan damai sejahtera di bumi di antara manusia yang berkenan kepada-Nya.", reference: "Lukas 2:14" },
  { text: "Roh Tuhan ada pada-Ku, oleh sebab Ia telah mengurapi Aku, untuk menyampaikan kabar baik kepada orang-orang miskin.", reference: "Lukas 4:18" },
  { text: "Hendaklah kamu murah hati, sama seperti Bapamu adalah murah hati.", reference: "Lukas 6:36" },
  { text: "Berilah dan kamu akan diberi: suatu takaran yang baik, yang dipadatkan, yang digoncang dan yang tumpah ke luar akan dicurahkan ke dalam ribaanmu.", reference: "Lukas 6:38" },
  { text: "Sebab Anak Manusia datang untuk mencari dan menyelamatkan yang hilang.", reference: "Lukas 19:10" },
  { text: "Bapa, ke dalam tangan-Mu Kuserahkan nyawa-Ku.", reference: "Lukas 23:46" },
  { text: "Karena begitu besar kasih Allah akan dunia ini, sehingga Ia telah mengaruniakan Anak-Nya yang tunggal, supaya setiap orang yang percaya kepada-Nya tidak binasa, melainkan beroleh hidup yang kekal.", reference: "Yohanes 3:16" },
  { text: "Tetapi barangsiapa minum air yang akan Kuberikan kepadanya, ia tidak akan haus untuk selama-lamanya.", reference: "Yohanes 4:14" },
  { text: "Allah itu Roh dan barangsiapa menyembah Dia, harus menyembah-Nya dalam roh dan kebenaran.", reference: "Yohanes 4:24" },
  { text: "Akulah roti hidup; barangsiapa datang kepada-Ku, ia tidak akan lapar lagi, dan barangsiapa percaya kepada-Ku, ia tidak akan haus lagi.", reference: "Yohanes 6:35" },
  { text: "Akulah terang dunia; barangsiapa mengikut Aku, ia tidak akan berjalan dalam kegelapan, melainkan ia akan mempunyai terang hidup.", reference: "Yohanes 8:12" },
  { text: "Dan kamu akan mengetahui kebenaran, dan kebenaran itu akan memerdekakan kamu.", reference: "Yohanes 8:32" },
  { text: "Pencuri datang hanya untuk mencuri dan membunuh dan membinasakan; Aku datang, supaya mereka mempunyai hidup, dan mempunyainya dalam segala kelimpahan.", reference: "Yohanes 10:10" },
  { text: "Akulah gembala yang baik. Gembala yang baik memberikan nyawanya bagi domba-dombanya.", reference: "Yohanes 10:11" },
  { text: "Akulah kebangkitan dan hidup; barangsiapa percaya kepada-Ku, ia akan hidup walaupun ia sudah mati.", reference: "Yohanes 11:25" },
  { text: "Aku memberikan perintah baru kepada kamu, yaitu supaya kamu saling mengasihi; sama seperti Aku telah mengasihi kamu.", reference: "Yohanes 13:34" },
  { text: "Akulah pokok anggur dan kamulah ranting-rantingnya. Barangsiapa tinggal di dalam Aku dan Aku di dalam dia, ia berbuah banyak, sebab di luar Aku kamu tidak dapat berbuat apa-apa.", reference: "Yohanes 15:5" },
  { text: "Tidak ada kasih yang lebih besar dari pada kasih seorang yang memberikan nyawanya untuk sahabat-sahabatnya.", reference: "Yohanes 15:13" },
  { text: "Tetapi kamu akan menerima kuasa, kalau Roh Kudus turun ke atas kamu, dan kamu akan menjadi saksi-Ku.", reference: "Kisah Para Rasul 1:8" },
  { text: "Dan keselamatan tidak ada di dalam siapapun juga selain di dalam Dia, sebab di bawah kolong langit ini tidak ada nama lain yang diberikan kepada manusia yang olehnya kita dapat diselamatkan.", reference: "Kisah Para Rasul 4:12" },
  { text: "Sebab aku mempunyai keyakinan yang kokoh dalam Injil, karena Injil adalah kekuatan Allah yang menyelamatkan setiap orang yang percaya.", reference: "Roma 1:16" },
  { text: "Akan tetapi Allah menunjukkan kasih-Nya kepada kita, oleh karena Kristus telah mati untuk kita, ketika kita masih berdosa.", reference: "Roma 5:8" },
  { text: "Demikianlah sekarang tidak ada penghukuman bagi mereka yang ada di dalam Kristus Yesus.", reference: "Roma 8:1" },
  { text: "Roh membantu kita dalam kelemahan kita; sebab kita tidak tahu, bagaimana sebenarnya harus berdoa; tetapi Roh sendiri berdoa untuk kita kepada Allah dengan keluhan-keluhan yang tidak terucapkan.", reference: "Roma 8:26" },
  { text: "Tetapi dalam semuanya itu kita lebih dari pada orang-orang yang menang, oleh Dia yang telah mengasihi kita.", reference: "Roma 8:37" },
  { text: "Sebab aku yakin, bahwa baik maut, maupun hidup... tidak akan dapat memisahkan kita dari kasih Allah, yang ada dalam Kristus Yesus, Tuhan kita.", reference: "Roma 8:38-39" },
  { text: "Janganlah kamu menjadi serupa dengan dunia ini, tetapi berubahlah oleh pembaharuan budimu.", reference: "Roma 12:2" },
  { text: "Bersukacitalah dalam pengharapan, sabarlah dalam kesesakan, dan bertekunlah dalam doa!", reference: "Roma 12:12" },
  { text: "Janganlah kamu kalah terhadap kejahatan, tetapi kalahkanlah kejahatan dengan kebaikan!", reference: "Roma 12:21" },
  { text: "Semoga Allah, sumber pengharapan, memenuhi kamu dengan segala sukacita dan damai sejahtera dalam iman kamu.", reference: "Roma 15:13" },
  { text: "Sebab pemberitaan tentang salib memang adalah kebodohan bagi mereka yang akan binasa, tetapi bagi kita yang diselamatkan pemberitaan itu adalah kekuatan Allah.", reference: "1 Korintus 1:18" },
  { text: "Apa yang tidak pernah dilihat oleh mata, dan tidak pernah didengar oleh telinga, dan yang tidak pernah timbul di dalam hati manusia: semua yang disediakan Allah untuk mereka yang mengasihi Dia.", reference: "1 Korintus 2:9" },
  { text: "Tidak tahukah kamu, bahwa kamu adalah bait Allah dan bahwa Roh Allah diam di dalam kamu?", reference: "1 Korintus 3:16" },
  { text: "Pencobaan-pencobaan yang kamu alami ialah pencobaan-pencobaan biasa, yang tidak melebihi kekuatan manusia. Sebab Allah setia dan karena itu Ia tidak akan membiarkan kamu dicobai melampaui kekuatanmu.", reference: "1 Korintus 10:13" },
  { text: "Demikianlah tinggal ketiga hal ini, yaitu iman, pengharapan dan kasih, dan yang paling besar di antaranya ialah kasih.", reference: "1 Korintus 13:13" },
  { text: "Tetapi syukur kepada Allah, yang telah memberikan kepada kita kemenangan oleh Yesus Kristus, Tuhan kita.", reference: "1 Korintus 15:57" },
  { text: "Berjaga-jagalah! Berdirilah dengan teguh dalam iman! Bersikaplah sebagai laki-laki! Dan tetap kuat!", reference: "1 Korintus 16:13" },
  { text: "Lakukanlah segala pekerjaanmu dalam kasih!", reference: "1 Korintus 16:14" },
  { text: "Sebab firman Allah adalah ya bagi semua janji Allah. Itulah sebabnya oleh Dia kita mengatakan 'Amin' untuk memuliakan Allah.", reference: "2 Korintus 1:20" },
  { text: "Sebab hidup kami ini adalah hidup karena percaya, bukan karena melihat.", reference: "2 Korintus 5:7" },
  { text: "Jadi siapa yang ada di dalam Kristus, ia adalah ciptaan baru: yang lama sudah berlalu, sesungguhnya yang baru sudah datang.", reference: "2 Korintus 5:17" },
  { text: "Cukuplah kasih karunia-Ku bagimu, sebab justru dalam kelemahanlah kuasa-Ku menjadi sempurna.", reference: "2 Korintus 12:9" },
  { text: "Namun aku hidup, tetapi bukan lagi aku sendiri yang hidup, melainkan Kristus yang hidup di dalam aku.", reference: "Galatia 2:20" },
  { text: "Tetapi buah Roh ialah: kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan, kelemahlembutan, penguasaan diri.", reference: "Galatia 5:22-23" },
  { text: "Janganlah kita jemu-jemu berbuat baik, karena apabila sudah datang waktunya, kita akan menuai, jika kita tidak menjadi lemah.", reference: "Galatia 6:9" },
  { text: "Sebab karena kasih karunia kamu diselamatkan oleh iman; itu bukan hasil usahamu, tetapi pemberian Allah.", reference: "Efesus 2:8" },
  { text: "Karena kita ini buatan Allah, diciptakan dalam Kristus Yesus untuk melakukan pekerjaan baik.", reference: "Efesus 2:10" },
  { text: "Bagi Dialah, yang dapat melakukan jauh lebih banyak dari pada yang kita doakan atau pikirkan, seperti yang ternyata dari kuasa yang bekerja di dalam kita.", reference: "Efesus 3:20" },
  { text: "Hendaklah kamu ramah seorang terhadap yang lain, penuh kasih mesra dan saling mengampuni, sebagaimana Allah di dalam Kristus telah mengampuni kamu.", reference: "Efesus 4:32" },
  { text: "Karena bagiku hidup adalah Kristus dan mati adalah keuntungan.", reference: "Filipi 1:21" },
  { text: "Hendaklah kamu dalam hidupmu bersama, menaruh pikiran dan perasaan yang terdapat juga dalam Kristus Yesus.", reference: "Filipi 2:5" },
  { text: "Allahku akan memenuhi segala keperluanmu menurut kekayaan dan kemuliaan-Nya dalam Kristus Yesus.", reference: "Filipi 4:19" },
  { text: "Ia adalah gambar Allah yang tidak kelihatan, yang sulung, lebih utama dari segala yang diciptakan.", reference: "Kolose 1:15" },
  { text: "Dan di atas semuanya itu: kenakanlah kasih, sebagai pengikat yang mempersatukan dan menyempurnakan.", reference: "Kolose 3:14" },
  { text: "Hendaklah damai sejahtera Kristus memerintah dalam hatimu.", reference: "Kolose 3:15" },
  { text: "Apapun juga yang kamu perbuat, perbuatlah dengan segenap hatimu seperti untuk Tuhan dan bukan untuk manusia.", reference: "Kolose 3:23" },
  { text: "Semoga Allah damai sejahtera menguduskan kamu seluruhnya... Ia yang memanggil kamu adalah setia, Ia juga akan menggenapinya.", reference: "1 Tesalonika 5:23-24" },
  { text: "Tetapi Tuhan adalah setia. Ia akan menguatkan hatimu dan memelihara kamu terhadap yang jahat.", reference: "2 Tesalonika 3:3" },
  { text: "Sebab Allah memberikan kepada kita bukan roh ketakutan, melainkan roh yang membangkitkan kekuatan, kasih dan ketertiban.", reference: "2 Timotius 1:7" },
  { text: "Aku telah mengakhiri pertandingan yang baik, aku telah mencapai garis akhir dan aku telah memelihara iman.", reference: "2 Timotius 4:7" },
  { text: "Sebab firman Allah hidup dan kuat dan lebih tajam dari pada pedang bermata dua manapun.", reference: "Ibrani 4:12" },
  { text: "Sebab itu marilah kita dengan penuh keberanian menghampiri takhta kasih karunia, supaya kita menerima rahmat dan menemukan kasih karunia untuk mendapat pertolongan kita pada waktunya.", reference: "Ibrani 4:16" },
  { text: "Yesus Kristus tetap sama, baik kemarin maupun hari ini dan sampai selama-lamanya.", reference: "Ibrani 13:8" },
  { text: "Tetapi hendaklah ia memintanya dalam iman, dan sama sekali jangan bimbang.", reference: "Yakobus 1:6" },
  { text: "Setiap pemberian yang baik dan setiap anugerah yang sempurna, datangnya dari atas, diturunkan dari Bapa segala terang.", reference: "Yakobus 1:17" },
  { text: "Tetapi hendaklah kamu menjadi pelaku firman dan bukan hanya pendengar saja.", reference: "Yakobus 1:22" },
  { text: "Karena itu tunduklah kepada Allah, dan lawanlah Iblis, maka ia akan lari dari padamu!", reference: "Yakobus 4:7" },
  { text: "Terpujilah Allah dan Bapa Tuhan kita Yesus Kristus, yang karena rahmat-Nya yang besar telah melahirkan kita kembali oleh kebangkitan Yesus Kristus dari antara orang mati, kepada suatu hidup yang penuh pengharapan.", reference: "1 Petrus 1:3" },
  { text: "Tetapi kamulah bangsa yang terpilih, imamat yang rajani, bangsa yang kudus, umat kepunyaan Allah sendiri.", reference: "1 Petrus 2:9" },
  { text: "Tetapi kuduskanlah Kristus di dalam hatimu sebagai Tuhan! Dan siap sedialah pada segala waktu untuk memberi pertanggungan jawab kepada tiap-tiap orang yang meminta pertanggungan jawab dari kamu tentang pengharapan yang ada padamu.", reference: "1 Petrus 3:15" },
  { text: "Kasihilah sungguh-sungguh seorang akan yang lain, sebab kasih menutupi banyak sekali dosa.", reference: "1 Petrus 4:8" },
  { text: "Jika kita mengaku dosa kita, maka Ia adalah setia dan adil, sehingga Ia akan mengampuni segala dosa kita dan menyucikan kita dari segala kejahatan.", reference: "1 Yohanes 1:9" },
  { text: "Lihatlah, betapa besarnya kasih yang dikaruniakan Bapa kepada kita, sehingga kita disebut anak-anak Allah, dan memang kita adalah anak-anak Allah.", reference: "1 Yohanes 3:1" },
  { text: "Kita mengasihi, karena Allah lebih dahulu mengasihi kita.", reference: "1 Yohanes 4:19" },
  { text: "Dan inilah keberanian percaya kita kepada-Nya, yaitu bahwa Ia mengabulkan doa kita, jikalau kita meminta sesuatu kepada-Nya menurut kehendak-Nya.", reference: "1 Yohanes 5:14" },
  { text: "Bagi Dia, yang berkuasa menjaga supaya jangan kamu tersandung dan yang membawa kamu dengan tak bernoda dan penuh kegirangan di hadapan kemuliaan-Nya.", reference: "Yudas 1:24" },
  { text: "Lihatlah, Aku berdiri di muka pintu dan mengetok; jikalau jikalau ada orang mendengar suara-Ku dan membukakan pintu, Aku akan masuk mendapatkannya dan Aku makan bersama-sama dengan dia, dan ia bersama-sama dengan Aku.", reference: "Wahyu 3:20" },
  { text: "Dan Ia akan menghapus segala air mata dari mata mereka, dan maut tidak akan ada lagi; tidak akan ada lagi perkabungan, atau ratap tangis, atau dukacita.", reference: "Wahyu 21:4" },
  { text: "Lihatlah, Aku menjadikan segala sesuatu baru!", reference: "Wahyu 21:5" },
  { text: "Aku adalah Alfa dan Omega, Yang Pertama dan Yang Terkemudian, Yang Awal dan Yang Akhir.", reference: "Wahyu 22:13" },
  { text: "Kasih karunia Tuhan Yesus menyertai kamu sekalian! Amin.", reference: "Wahyu 22:21" }
];
